<?php
    define('DOMAIN', 'http://myform:8888/');
?>

<!DOCTYPE html>
<html lang="de" class="no-js">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">

	<title>Formular VALID</title>
	<meta name="description" content="Testaufgabe Formular">

	<!-- Canonical URL specify for search engines -->
	<link rel="canonical" href="<?php echo DOMAIN; ?>"/>

	<!-- Load master.css now, generated by scssphp -->
	<link href="<?php echo DOMAIN; ?>/assets/scss/master.css" rel="stylesheet" type="text/css">

</head>

<body id="top">
test
</body>

<footer></footer>