<?php
    define('DOMAIN', 'http://myform:8888/');
?>

<!DOCTYPE html>
<html lang="de" class="no-js">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">

	<title>Formular VALID</title>
	<meta name="description" content="Testaufgabe Formular">

	<!-- Canonical URL specify for search engines -->
	<link rel="canonical" href="<?php echo DOMAIN; ?>"/>

	<!-- Load master.css now, generated by scssphp -->
	<link href="<?php echo DOMAIN; ?>/assets/scss/master.css" rel="stylesheet" type="text/css">

</head>

<body id="top">
	<section>
	<form action="form-processing.php" method="post">
			
			<label for="title">Anrede*</label>
			<input type="text" id="title" name="title" required><br>
			<label for="fullname">Name*</label>
			<input type="text" id="fullname" name="fullname" required><br>
			<label for="email">E-Mail*</label>
			<input type="text" id="email" name="email" required>
			<span class="error" id="invalid_email">Diese E-Mail ist ungültig</span><br>
			
			<div class="form-group">
			<label for="request">Anfrage*</label><br>
			<select id="request" name="request" required>
				<option value="option1">Option 1</option>
				<option value="option2">Option 2</option>
				<option value="option3">Option 3</option>
			</select><br>
			</div>

			<div class="form-group" id="descriptiontext_div">
				<label for="descriptiontext">Beschreibungstext:</label>
				<input type="text" id="descriptiontext" name="descriptiontext"><br>
			</div>

			<input type="checkbox" name="dataprivacy" id="dataprivacy" required />
			<label for="dataprivacy">Ich habe die Datenschutzerklärung zur Kenntnis genommen. Ich stimme zu, dass meine Angaben und Daten zur Beantwortung meiner Anfrage elektronisch erhoben und gespeichert werden.</label>
			<br>

			<input type="submit" id="submit">
		</form>
	
	
	</section>


</body>

<footer></footer>