<?php
    define('DOMAIN', 'http://myform:8888/');
?>

<!DOCTYPE html>
<html lang="de" class="no-js">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">

	<title>Formular VALID</title>
	<meta name="description" content="Testaufgabe Formular">

	<!-- Canonical URL specify for search engines -->
	<link rel="canonical" href="<?php echo DOMAIN; ?>"/>

	<!-- Load master.css now, generated by scssphp -->
	<link href="<?php echo DOMAIN; ?>/assets/scss/master.css" rel="stylesheet" type="text/css">

</head>

<body id="top">
	<section>
	<div class="container">
	<h1>Kontaktformular</h1>
	<form action="form-processing.php" method="post">
			
			<div class="form-item form-item__small">
				<label for="title">Anrede*</label><br>
				<input class="form-item__input" type="text" id="title" name="title" required>
			</div>
			<div class="form-item form-item__small">
				<label for="fullname">Name*</label><br>
				<input class="form-item__input" type="text" id="fullname" name="fullname" required><br>
			</div>

			<div class="form-item">
				<label for="email">E-Mail*</label><br>
				<input class="form-item__input" type="text" id="email" name="email" required><br>
				<span class="error" id="invalid_email">Diese E-Mail ist ungültig</span><br>
			</div>

			<div class="form-item">
			<label for="request">Anfrage*</label><br>
			<select class="form-item__select" id="request" name="request" required>
				<option value="option1">Option 1</option>
				<option value="option2">Option 2</option>
				<option value="option3">Option 3</option>
			</select><br>
			</div>

			<div class="form-item" id="descriptiontext_div"><br>
				<label for="descriptiontext">Beschreibungstext:</label>
				<input class="form-item__input" type="text" id="descriptiontext" name="descriptiontext"><br>
			</div>

			<div class="form-item">
				<input class="form-item__checkbox" type="checkbox" name="dataprivacy" id="dataprivacy" required />
				<label for="dataprivacy" class="small">Ich habe die Datenschutzerklärung zur Kenntnis genommen. Ich stimme zu, dass meine Angaben und Daten zur Beantwortung meiner Anfrage elektronisch erhoben und gespeichert werden.</label>
			</div>

			<input type="submit" id="submit">
		</form>
		</div>
	
	</section>

	<footer>
	</footer>

</body>
</html>
